version: "3"

services:
  blog:
    build:
      context: ./client

    volumes:
      - react_build:/react/dist

  server:
    build:
      context: ./server
    command: gunicorn server.wsgi --bind 0.0.0.0:9100
    ports:
      - 9100:9100

  nginx:
    image: nginx:latest
    ports:
      - 5000:80

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/react

    depends_on:
      - server
      - blog

volumes:
  react_build:
